-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 08:49:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema lr2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lr2` DEFAULT CHARACTER SET utf8 ;
USE `lr2` ;

-- -----------------------------------------------------
-- Table `lr2`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lr2`.`Student` (
  `student_id` INT NOT NULL,
  `full_name` VARCHAR(100) NULL,
  `date_of_birth` DATE NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lr2`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lr2`.`Teacher` (
  `teacher_id` INT NOT NULL,
  `full_name` VARCHAR(100) NULL,
  PRIMARY KEY (`teacher_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lr2`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lr2`.`Subject` (
  `subject_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `semester` INT NULL,
  `Teacher_teacher_id` INT NOT NULL,
  PRIMARY KEY (`subject_id`),
  INDEX `fk_Subject_Teacher_idx` (`Teacher_teacher_id` ASC) VISIBLE,
  CONSTRAINT `fk_Subject_Teacher`
    FOREIGN KEY (`Teacher_teacher_id`)
    REFERENCES `mydb`.`Teacher` (`teacher_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lr2`.`Grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lr2`.`Grade` (
  `grade` INT NULL,
  `Subject_subject_id` INT NOT NULL,
  `Student_student_id` INT NOT NULL,
  INDEX `fk_Grade_Subject1_idx` (`Subject_subject_id` ASC) VISIBLE,
  INDEX `fk_Grade_Student1_idx` (`Student_student_id` ASC) VISIBLE,
  PRIMARY KEY (`Subject_subject_id`, `Student_student_id`),
  CONSTRAINT `fk_Grade_Subject1`
    FOREIGN KEY (`Subject_subject_id`)
    REFERENCES `mydb`.`Subject` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grade_Student1`
    FOREIGN KEY (`Student_student_id`)
    REFERENCES `mydb`.`Student` (`student_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
